# Generated by Django 4.1.1 on 2022-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_posttype_post_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(related_name='news', through='app1.PostCategory', to='app1.category'),
        ),
    ]
