# Generated by Django 4.1.1 on 2022-10-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='app1.PostCategory', to='app1.category'),
        ),
    ]
