# Generated by Django 4.1.1 on 2022-10-16 23:35

import app1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_post_postcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[app1.validators.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, validators=[app1.validators.validate_not_empty]),
        ),
    ]
